name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libta-lib0 libta-lib0-dev
          sudo apt-get install -y python3-dev python3-pip python3-setuptools
          sudo apt-get install -y pkg-config
      
      - name: Install Python dependencies
        env:
          LD_LIBRARY_PATH: /usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.24.3
          pip install pandas==2.0.3
          pip install ta-lib==0.6.3
          pip install -r requirements.txt
      
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          LD_LIBRARY_PATH: /usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
        run: |
          pytest tests/ --cov=src/ --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/volatility-bot:latest
            ${{ secrets.DOCKER_USERNAME }}/volatility-bot:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/volatility-bot:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/volatility-bot:buildcache,mode=max
