name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Build TA-Lib C library
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y build-essential wget libtool autoconf automake

          wget -q http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib

          ./configure --prefix=/usr \
              --disable-tools --disable-examples --disable-samples

          # 순서대로 빌드 (의존성 순서 고려)
          make -C src/ta_common   -j1
          make -C src/ta_abstract -j1
          make -C src/ta_func     -j1
          make -C src             -j1 libta_lib.la
          sudo make -C src install
          
          # Set environment variables for Python binding
          export TA_INCLUDE_PATH=/usr/include
          export TA_LIBRARY_PATH=/usr/lib
          sudo ldconfig
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # NumPy 1.24 이하 고정
          pip install "numpy<1.24" pandas==1.5.3
          
          # TA-Lib 설치 (빌드 격리 비활성화)
          pip install --no-build-isolation ta-lib==0.4.28
          
          # pytest와 관련 의존성 설치
          pip install pytest==7.4.0 pytest-cov==4.1.0 pytest-mock==3.11.1 pluggy>=1.0.0
          
          # 누락된 의존성 패키지 설치
          pip install PyJWT pygments
          
          # 나머지 패키지
          pip install --no-deps -r requirements.txt
      
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/ --cov=src/ --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  build-and-push:
    needs: test
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/volatility-bot:latest
            ${{ secrets.DOCKER_USERNAME }}/volatility-bot:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/volatility-bot:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/volatility-bot:buildcache,mode=max
